CREATE PROCEDURE BILLMONTH
AS
BEGIN
SELECT product_name FROM
(
SELECT product_name, COUNT('X') ENNDDATE FROM
(
SELECT CONTRACTID, STARTDATE, ENDDATE, contract_type FROM
CONTRACTS
JOIN
PRODUCTS
ON (CONTRACTS.contract_type=PRODUCTS)
WHERE(SYSDATE<CONTRACTS.ENDDATE)
)
GROUP BY product_name
ORDER BY ENDDATE ASC
)
WHERE (ENDDATE>=01-01-2016 AND ENDDATE <= 31-12-2016)
END BILLMONTH; 
