SELECT TOP 5 ACTOR
FROM
(SELECT ACTOR, count('x') performances FROM
 (SELECT ACTOR, TITLE
  FROM CASTS JOIN
  MOVIES
  ON (CASTS.TITLE=MOVIES.MOVIE_TITLE)
  WHERE (MOVIES.COUNTRY='USA')
  )
  GROUP BY ACTOR)
  ORDER BY performances DESC;
