
--Query with count added
SELECT SURNAME, NAME, STARTDATE, ENDDATE, TYPE
  FROM PRODUCTS JOIN (CLIENTS JOIN CONTRACTS ON (CLIENTS.CLIENTID=CONTRACTS.CLIENTID)) ON (PRODUCTS.PRODUCT_NAME=CONTRACTS.CONTRACT_TYPE)
  WHERE ((SYSDATE<CONTRACTS.ENDDATE AND SYSDATE>CONTRACTS.STARTDATE) OR (SYSDATE>STARTDATE AND ENDDATE IS NULL))
  ORDER BY SURNAME, NAME ASC;
