CREATE OR REPLACE TRIGGER TRIGGER_2
AFTER INSERT ON
TAPS_MOVIES
DECLARE
C1 CONTRACTS.STARTDATE%TYPE
C2 CONTRACTS.ENDDATE%TYPE
BEGIN
IF INSERTING THEN
  SELECT INTO C1
  SELECT STARTDATE FROM
  (
  CONTRACTID, STARTDATE, ENDDATE, VIEW_DATETIME FROM
  CONTRACTS
  NATURAL JOIN
  TAPS_MOVIES
);
  SELECT INTO C2
  SELECT ENDDATE FROM
  (
  CONTRACTID, STARTDATE, ENDDATE, VIEW_DATETIME FROM
  CONTRACTS
  NATURAL JOIN
  TAPS_MOVIES
);
IF C1>VIEW_DATETIME OR C2<VIEW_DATETIME OR SYSDATE<VIEW_DATETIME
THEN
RAISE_APLICATION_ERROR(20001,'DATE IS NOT CORRECT')
END IF;
END IF;
END
;
/
