CREATE OR REPLACE TRIGGER TRIGGER_2
AFTER INSERT ON
TAPS_MOVIES
DECLARE
C1 CONTRACTS.STARTDATE%TYPE;
C2 CONTRACTS.ENDDATE%TYPE;
BEGIN
IF INSERTING THEN
  SELECT STARTDATE, ENDDATE INTO C1, C2
  FROM
  (
  SELECT
  CONTRACTID, STARTDATE, ENDDATE, VIEW_DATETIME FROM
  CONTRACTS
  NATURAL JOIN
  TAPS_MOVIES
);
IF C1>VIEW_DATETIME OR C2<VIEW_DATETIME OR SYSDATE<VIEW_DATETIME
THEN
RAISE_APLICATION_ERROR(20001,'DATE IS NOT CORRECT')
END IF;
END IF;
END
;
/
