CREATE VIEW TOPCONTENT AS
SELECT *
FROM ((SELECT *
      FROM(SELECT TITLE, SUM(PRODUCTS.FEE) AS SUM
        FROM CONTRACTS JOIN TAPS_MOVIES ON (CONTRACTS.CONTRACTID=TAPS_MOVIES.CONTRACTID)
                       JOIN PRODUCTS ON (CONTRACT_TYPE=PRODUCTS.PRODUCT_NAME)
        GROUP BY TITLE
        ORDER BY SUM DESC)
        WHERE ROWNUM<2
       ) UNION
      (SELECT *
      FROM(SELECT TAPS_SERIES.TITLE, SUM(PRODUCTS.FEE) AS SUM
            FROM CONTRACTS JOIN TAPS_SERIES ON (CONTRACTS.CONTRACTID=TAPS_SERIES.CONTRACTID)
                           JOIN PRODUCTS ON (CONTRACT_TYPE=PRODUCTS.PRODUCT_NAME)
            GROUP BY TAPS_SERIES.TITLE
            ORDER BY SUM DESC)
            WHERE ROWNUM<2
       )
      )
ORDER BY SUM DESC
WHERE ROWNUM<2;
