DROP VIEW view_name;

--TO CHECK IF VIEW WORKS
SELECT * FROM VIEW;

CREATE VIEW view_name AS
SELECT column1, column2, ...
FROM table_name
WHERE condition;


CREATE OR REPLACE VIEW BACALA AS 
SELECT * FROM
(SELECT TITLE 
FROM (SELECT TITLE, PCT FROM TAPS_MOVIES WHERE (PCT>50 AND PCT<97)) 
GROUP BY TITLE 
ORDER BY COUNT(PCT) DESC) 
WHERE ROWNUM<=5;






