CREATE VIEW ALL AS
SELECT *
FROM MOVIES JOIN GENRES ON (MOVIES.TITLE=GENRES.TITLE) AS AUX1
            JOIN KEYWORDS_MOVIES ON (AUX1.TITLE=KEYWORDS_MOVIES.TITLE) AS AUX2
            JOIN (SELECT * FROM CASTS LEFT JOIN PLAYERS ON (CASTS.ACTOR=PLAYERS.ACTOR_NAME) AS AUX3) ON (AUX2.TITLE=AUX3.TITLE)

WHERE TITLE!= NULL;



--Get the proper format on the actor number

SELECT SUBSTR(ACTORLIST, 1, INSTR(ACTORLIST, ';', 1, 1)-1) AS ACTOR1,
       SUBSTR(ACTORLIST, INSTR(ACTORLIST, ';',1, 1)+1, INSTR(ACTORLIST, ';',1, 2)-1) AS ACTOR2,
       SUBSTR(ACTORLIST,(INSTR(ACTORLIST, ';',1, 2)+1)) AS ACTOR3
FROM (SELECT LISTAGG(ACTOR_NAME, ';') WITHIN GROUP (ORDER BY ACTOR_NAME) AS ACTORLIST
      FROM (SELECT *
            FROM CASTS LEFT JOIN PLAYERS ON (CASTS.ACTOR=PLAYERS.ACTOR_NAME)));



SELECT SUBSTR(LISTAGG(ACTOR_NAME, ';') WITHIN GROUP (ORDER BY ACTOR_NAME), 1, INSTR(LISTAGG(ACTOR_NAME, ';') WITHIN GROUP (ORDER BY ACTOR_NAME), ';', 1, 1)-1) AS ACTOR1,
       SUBSTR(LISTAGG(ACTOR_NAME, ';') WITHIN GROUP (ORDER BY ACTOR_NAME), INSTR(LISTAGG(ACTOR_NAME, ';') WITHIN GROUP (ORDER BY ACTOR_NAME), ';',1, 1)+1, INSTR(LISTAGG(ACTOR_NAME, ';') WITHIN GROUP (ORDER BY ACTOR_NAME), ';',1, 2)-1) AS ACTOR2,
       SUBSTR(LISTAGG(ACTOR_NAME, ';') WITHIN GROUP (ORDER BY ACTOR_NAME),(INSTR(LISTAGG(ACTOR_NAME, ';') WITHIN GROUP (ORDER BY ACTOR_NAME), ';',1, 2)+1)) AS ACTOR3
FROM CASTS LEFT JOIN PLAYERS ON (ACTOR=PLAYERS.ACTOR_NAME);
