SELECT TITLE, MONTHMAX, A.MON FROM
(
(SELECT MON, MAX(TOTALSUM) AS MONTHMAX
		FROM
    (
      SELECT TITLE, TO_CHAR(VIEW_DATETIME, 'MON-YYYY') AS MON, SUM(FEE) AS TOTALSUM
			  FROM
        (
        (
          CONTRACTS
        NATURAL JOIN
        TAPS_MOVIES)
					JOIN PRODUCTS ON (CONTRACT_TYPE=PRODUCTS.PRODUCT_NAME)
        )
			GROUP BY TITLE, TO_CHAR(VIEW_DATETIME, 'MON-YYYY')
      ORDER BY TITLE ASC
			)
			GROUP BY MON
      ORDER BY MON DESC
			)A
      JOIN
      (
        SELECT TITLE, TO_CHAR(VIEW_DATETIME, 'MON-YYYY') AS MON, SUM(FEE) AS TOTALSUM
  			  FROM
          (
          (
            CONTRACTS
          NATURAL JOIN
          TAPS_MOVIES)
  					JOIN PRODUCTS ON (CONTRACT_TYPE=PRODUCTS.PRODUCT_NAME)
          )
  			GROUP BY TITLE, TO_CHAR(VIEW_DATETIME, 'MON-YYYY')
        ORDER BY TITLE ASC
      )B
      ON (MONTHMAX=TOTALSUM AND A.MON=B.MON)
		)
      ORDER BY TO_DATE(A.MON, 'MON-YYYY')
      ;
		--RETURNS TOP SCORE OF EVERY MONTH
