CREATE OR REPLACE VIEW TOPCONTENT AS
SELECT *
FROM(SELECT *
		FROM( SELECT *
			  FROM ( SELECT TITLE, 0 AS SEASON, 0 AS EPISODE, TOTALSUM
				FROM(SELECT A.TITLE, COALESCE (B.SEASON, 0) AS SEASON, COALESCE(B.EPISODE, 0) AS EPISODE,  A.TOTALSUM AS TOTALSUM
					FROM(SELECT TITLE, TOTALSUM
							FROM(SELECT TITLE, SUM(PRODUCTS.FEE) AS TOTALSUM
								FROM CONTRACTS JOIN TAPS_MOVIES ON (CONTRACTS.CONTRACTID=TAPS_MOVIES.CONTRACTID)
											   JOIN PRODUCTS ON (CONTRACT_TYPE=PRODUCTS.PRODUCT_NAME)
								GROUP BY TITLE
								ORDER BY TOTALSUM DESC)
								WHERE ROWNUM<2
						 ) A
						LEFT OUTER JOIN
						(SELECT *
							FROM(SELECT TAPS_SERIES.TITLE, SEASON, EPISODE, SUM(PRODUCTS.FEE) AS TOTALSUM
								FROM CONTRACTS JOIN TAPS_SERIES ON (CONTRACTS.CONTRACTID=TAPS_SERIES.CONTRACTID)
											   JOIN PRODUCTS ON (CONTRACT_TYPE=PRODUCTS.PRODUCT_NAME)
								GROUP BY TAPS_SERIES.TITLE, SEASON, EPISODE
								ORDER BY TOTALSUM DESC)
								WHERE ROWNUM<2
						 ) B
						ON A.TITLE NOT LIKE B.TITLE --Now we have movie with season and episode attributes set to 0
				)
			  )
			  UNION
				(SELECT *
					FROM(SELECT TAPS_SERIES.TITLE, SEASON, EPISODE, SUM(PRODUCTS.FEE) AS TOTALSUM
						FROM CONTRACTS JOIN TAPS_SERIES ON (CONTRACTS.CONTRACTID=TAPS_SERIES.CONTRACTID)
									   JOIN PRODUCTS ON (CONTRACT_TYPE=PRODUCTS.PRODUCT_NAME)
						GROUP BY TAPS_SERIES.TITLE, SEASON, EPISODE
						ORDER BY TOTALSUM DESC)
						WHERE ROWNUM<2
				)
		)
						ORDER BY TOTALSUM DESC
)
WHERE ROWNUM<2;
